spring:
  application:
      name: project
  datasource:
    url: jdbc:mysql://localhost:3306/test
    name: balu
    password: balu
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: redis
  data:
    redis:
      timeout: 60000

